GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/6391ef1c995cf46c35860b9a

###

POST http://localhost:3000/contacts
Content-Type: application/json

{
    "contactName": "Micke Frick",
    "contactEmail": "micke@gmail.com",
    "contactTelephone": "070 123 45 67",
    "contactAddress": "Eriksbergsvägen 7 83143 Östersund",
    "contactGender": "Male"
  }

###


DELETE http://localhost:3000/contacts/


###


PATCH http://localhost:3000/contacts/6391ef1c995cf46c35860b9a
Content-Type: application/json

{ 

    "contactEmail" : "natalie@gmail.com"

}